apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service-dev
spec:
  selector:
    app: client-deployment-label-dev
  type: ClusterIP
  ports:
    - name: client-deployment-label-dev
      protocol: TCP
      port: 3000
      targetPort: 3000 