apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: client-deployment-label
  template:
    metadata:
      labels: 
        app: client-deployment-label
    spec: 
      containers:
        - name: client-deployment-container
          image: andorkovacs/k8s-test-client-docker-image
