apiVersion: v1
kind: Service
metadata:
  name: microservice-b-cluster-ip-service
spec:
  selector:
    app: microservice-b-deployment-label
  type: ClusterIP
  ports:
    - name: microservice-b-cluster-ip-service-port-name
      protocol: TCP
      port: 8081
      targetPort: 8081
