apiVersion: v1
kind: Service
metadata:
  name: microservice-a-cluster-ip-service
spec:
  selector:
    app: microservice-a-deployment-label
  type: ClusterIP
  ports:
    - name: microservice-a-cluster-ip-service-port-name
      protocol: TCP
      port: 8080
      targetPort: 8080 